<?php

namespace App\Contracts;

use App\Models\Central\TokenOrder;
use Illuminate\Http\Request;

interface PaymentGatewayContract
{
    /**
     * Create a payment order/transaction on the gateway.
     * 
     * Returns an array containing:
     * - 'payment_url' (string|null): URL to redirect customer or display in iframe
     * - 'snap_token' / 'token' (string|null): Token for frontend checkout popup (e.g. Midtrans Snap)
     * - 'gateway_order_id' (string|null): Transaction/Order ID generated by the gateway
     * - 'raw_response' (array): Full raw response from gateway
     */
    public function createOrder(TokenOrder $order, array $customerDetails = []): array;

    /**
     * Verify webhook signature / HMAC from the incoming HTTP request.
     */
    public function verifyWebhook(Request $request): bool;

    /**
     * Parse webhook payload and return normalized order status information.
     * 
     * Returns an array containing:
     * - 'order_id' (string): Our TokenOrder UUID (reference ID)
     * - 'gateway_order_id' (string|null): Transaction ID on gateway side
     * - 'status' (string): Normalized status ('success', 'pending', 'failed', 'expired')
     * - 'raw_payload' (array): Complete webhook payload for logging
     */
    public function parseWebhook(Request $request): array;
}
